import { ArrowLeft, ChevronLeft, ChevronRight, Cloud, CloudOff } from "lucide-react";

import { Link, useParams } from "react-router-dom";

import NotationGrid from "@/components/NotationGrid";

import useSaisie from "@/hooks/useSaisie";

export default function Saisie(){const {parcelleId,placetteId}=useParams(),s=useSaisie(parcelleId,placetteId);if(s.loading)return <div className="grid min-h-screen place-items-center">Chargement de la placette…</div>;const total=s.emplacements.length,complete=s.notations.length>=total;const prevCat=s.categories.find(c=>c.code===s.previousNotation?.code);const prevLabel=s.previousNotation?(prevCat?`${s.previousNotation.code} – ${prevCat.libelle}`:s.previousNotation.code):"Non renseignée";return <div className="min-h-screen bg-[#f4f7f3] p-4 pb-8"><div className="mx-auto max-w-xl"><div className="mb-4 flex items-center justify-between"><Link to={`/parcelles/${parcelleId}`} className="grid h-11 w-11 place-items-center rounded-xl bg-white shadow"><ArrowLeft/></Link><div className="text-center"><p className="text-xs font-bold text-emerald-700">{s.parcelle.identifiant} · Placette {s.placette.numero}</p><p className="font-black">Rang {s.placette.rang}</p></div><div className="grid h-11 w-11 place-items-center text-emerald-700">{navigator.onLine?<Cloud/>:<CloudOff/>}</div></div><div className="mb-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-emerald-700 transition-all" style={{width:`${total?((s.index+1)/total)*100:0}%`}}/></div>{complete&&<div className="mb-4 rounded-xl bg-emerald-100 p-3 text-center font-bold text-emerald-800">Placette terminée ✓</div>}<div className="mb-5 rounded-3xl bg-white p-5 text-center shadow-sm"><p className="text-sm text-slate-500">Emplacement</p><h1 className="text-4xl font-black text-slate-900">{s.current?.numero}</h1><p className="mt-1 font-semibold text-emerald-800">{s.index+1} / {total}</p><div className="mt-4 rounded-xl bg-slate-100 p-3"><p className="text-xs font-bold uppercase text-slate-500">Notation {s.year-1} · lecture seule</p><p className="mt-1 text-xl font-black">{prevLabel}</p></div></div><NotationGrid categories={s.categories} value={s.currentNotation?.code} onSelect={s.save} disabled={s.saving}/><div className="mt-5 flex gap-3"><button onClick={()=>s.setIndex(Math.max(0,s.index-1))} disabled={!s.index} className="flex h-14 flex-1 items-center justify-center gap-2 rounded-2xl border bg-white font-bold disabled:opacity-30"><ChevronLeft/>Précédent</button><button onClick={()=>s.setIndex(Math.min(total-1,s.index+1))} disabled={s.index>=total-1} className="flex h-14 flex-1 items-center justify-center gap-2 rounded-2xl bg-slate-900 text-white font-bold disabled:opacity-30">Suivant<ChevronRight/></button></div></div></div>}
